name: english_learning_app
description: "Kids English learning app with conversational AI features."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.3.1
  speech_to_text: ^7.1.0

  http: ^1.2.2
  firebase_storage: ^12.2.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3

  cloudinary_flutter: ^1.3.0
  cloudinary_url_gen: ^1.8.0

  # UI and Core Plugins
  cupertino_icons: ^1.0.8
  camera: ^0.11.0+1
  introduction_screen: ^3.1.14

  # AI and Text-to-Speech
  flutter_tts: ^4.0.2
  google_generative_ai: ^0.4.3

  # NEW: Packages for Audio Recording and Permissions
  flutter_sound: ^9.2.13
  permission_handler: ^12.0.0+1
  path_provider: ^2.1.3

  # --- Firebase Plugins ---
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9
  firebase_auth: ^5.6.0
  firebase_analytics: ^11.6.0
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  confetti: ^0.7.0
  just_audio: ^0.9.36

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  shared_preferences_platform_interface: ^2.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/map/
    - assets/images/words/
    - assets/data/levels.json

