name: english_learning_app
description: "Kids English learning app with conversational AI features."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI and Core Plugins
  cupertino_icons: ^1.0.8

  # AI and Speech Plugins
  flutter_tts: ^4.0.2
  google_generative_ai: ^0.4.3
#  speech_to_text: ^6.6.2 # Modern version that works with V2 Embedding

  # --- Firebase Plugins ---
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.4
  firebase_auth: ^4.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
